.TH "Catapult" 3 "Tue May 23 2017" "Smart Arduino Turret" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catapult
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Catapult\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCatapult\fP (int firePin, int armPin, int ballsPin, int platformPin)"
.br
.ti -1c
.RI "void \fBsweep\fP (Servo servo, int originAngle, int destinationAngle, int speed)"
.br
.ti -1c
.RI "void \fBrest\fP ()"
.br
.ti -1c
.RI "void \fBprepareToShoot\fP ()"
.br
.ti -1c
.RI "void \fBshoot\fP ()"
.br
.ti -1c
.RI "void \fBopenGate\fP ()"
.br
.ti -1c
.RI "void \fBcloseGate\fP ()"
.br
.ti -1c
.RI "void \fBfeedBall\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catapult::Catapult (int firePin, int armPin, int ballsPin, int platformPin)"

.SH "Member Function Documentation"
.PP 
.SS "void Catapult::closeGate ()"

.SS "void Catapult::feedBall ()"

.SS "void Catapult::openGate ()"

.SS "void Catapult::prepareToShoot ()"

.SS "void Catapult::rest ()"

.SS "void Catapult::shoot ()"

.SS "void Catapult::sweep (Servo servo, int originAngle, int destinationAngle, int speed)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Arduino Turret from the source code\&.
