.TH "D:/drkzt/Documents/Github Repos/Smart-Arduino-Turret/SAT Directory Reference" 3 "Tue May 23 2017" "Smart Arduino Turret" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/drkzt/Documents/Github Repos/Smart-Arduino-Turret/SAT Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCatapult\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCatapult\&.h\fP"
.br
.ti -1c
.RI "file \fBDisplay\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDisplay\&.h\fP"
.br
.ti -1c
.RI "file \fBSensor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSensor\&.h\fP"
.br
.in -1c
