.TH "Display" 3 "Tue May 23 2017" "Smart Arduino Turret" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Display
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Display\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplay\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Display::Display ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Arduino Turret from the source code\&.
