.TH "D:/drkzt/Documents/Github Repos/Smart-Arduino-Turret/SAT/Display.h" 3 "Wed May 24 2017" "Smart Arduino Turret" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/drkzt/Documents/Github Repos/Smart-Arduino-Turret/SAT/Display.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <Adafruit_GFX\&.h>\fP
.br
\fC#include <Adafruit_NeoPixel\&.h>\fP
.br
\fC#include <Adafruit_NeoMatrix\&.h>\fP
.br
\fC#include <LiquidCrystal\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDisplay\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBneoPixelMatrix\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define neoPixelMatrix"

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Arduino Turret from the source code\&.
