.TH "Sensor" 3 "Wed May 24 2017" "Smart Arduino Turret" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sensor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSensor\fP ()"
.br
.ti -1c
.RI "\fBSensor\fP (Ultrasonic mySensor)"
.br
.ti -1c
.RI "\fBSensor\fP (int triggerPin, int echoPin)"
.br
.ti -1c
.RI "bool \fBdetectTarget\fP (int range)"
.br
.ti -1c
.RI "uint8_t \fBgetDistanceMap\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sensor::Sensor ()"

.SS "Sensor::Sensor (Ultrasonic mySensor)"

.SS "Sensor::Sensor (int triggerPin, int echoPin)"

.SH "Member Function Documentation"
.PP 
.SS "bool Sensor::detectTarget (int range)"

.SS "uint8_t Sensor::getDistanceMap ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Arduino Turret from the source code\&.
