.TH "D:/drkzt/Documents/Github Repos/Smart-Arduino-Turret/SAT/Sensor.h" 3 "Tue May 23 2017" "Smart Arduino Turret" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/drkzt/Documents/Github Repos/Smart-Arduino-Turret/SAT/Sensor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <Ultrasonic\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_TRIGGER_PIN\fP   3"
.br
.ti -1c
.RI "#define \fBDEFAULT_ECHO_PIN\fP   2"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_ECHO_PIN   2"

.SS "#define DEFAULT_TRIGGER_PIN   3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Arduino Turret from the source code\&.
